### ISSUE TITLE
Differences to myoung34 image

### ISSUE THREAD

**Issue by Uzlopak** [evryfs/github-actions-runner#167]
HI @evryfs

are there significant differences between this runner-image and the one from myoung34?

**Comment by davidkarlsen** [comment]
It is very similar, only big difference is that we run as non-root by default.
Actually we have a derivate of the myoung image in this branch: https://github.com/evryfs/github-actions-runner/blob/myoung34-derivate/Dockerfile which adds some tools.

**Comment by Uzlopak** [comment]
Thank you for your feedback. There is currently  a PR for the myoung34 image to also run in non-root by default.

Do you have a built Docker Image in some repository? 

For us is also the k8 operator interesting. If the k8 operator works only with this image, we would consider to switch to your image. Does the operator also work with the myoung34 image?

**Comment by davidkarlsen** [comment]
https://github.com/evryfs/github-actions-runner-operator works with both images. basically it is the images that run the runners, while the operator handles registration and scaling.

**Comment by davidkarlsen** [comment]
Ah, and our images are hosted in quay: https://quay.io/organization/evryfs/

**Comment by Uzlopak** [comment]
Whoa! Super strange. When I build the Image locally it is 4,2 GB big. 

myoung34 image is "just" 1.2 GB. Super strange. 

![image](https://user-images.githubusercontent.com/5059100/180990412-22eb240e-1121-4e27-b85f-1138b77ad303.png)


Maybe it is better to smash all the apt installs together?

**Comment by davidkarlsen** [comment]
See https://github.com/evryfs/github-actions-runner/blob/myoung34-derivate/Dockerfile which is the derivate.
You can use https://github.com/wagoodman/dive to inspect the layers.
Size diff can also be compressed vs uncompressed.

**Comment by davidkarlsen** [comment]
no more comms, closing as fixed.
