### ISSUE TITLE
Pipeline broke because you deleted a tag

### ISSUE THREAD

**Issue by Cobesz** [evryfs/github-actions-runner#187]
I'm using your image as a base and today I wanted to update my image, but the build failed. It seems that this happens because you deleted the tag at Quay: 
![image](https://user-images.githubusercontent.com/7373155/192498905-bf1b8be1-ef79-4cbc-ad62-86b7a5e838ad.png)

![image](https://user-images.githubusercontent.com/7373155/192498688-22369add-48f9-49a5-ba06-8a6d936895df.png)

Can you please add a numbered tag instead of a regular "Master" tag?

**Comment by davidkarlsen** [comment]
that tag was so old that it would not be able to run anyways.
But yes, we can add tags as well.

**Comment by Cobesz** [comment]
I think tags like focal/20.04 or Jammy/22.04 would be awesome!

**Comment by Otterian** [comment]
Consider moving to the myoung34-derivative image, or forking the repository, as this PR will be the final update of the virtualenvironments image ever -> https://github.com/evryfs/github-actions-runner/pull/240

The reason for this is that we do not use that image any longer, and it's quite a heavy image to build and maintain.

Thank you.
