### ISSUE TITLE
Upgrade to virtual-env 20201026.1 for current image.

### ISSUE THREAD

**Issue by davidkarlsen** [evryfs/github-actions-runner#29]
https://github.com/actions/virtual-environments

@paolomainardi - want to join? See https://github.com/evryfs/github-actions-runner/pull/30 - but it seems to want a /toolset.json file - not sure about what's going on there.

**Comment by paolomainardi** [comment]
hi @davidkarlsen sure! i'll keep on eye on it later today or tomorrow.

**Comment by davidkarlsen** [comment]
@paolomainardi great - thanks - actually that PR is just upgrading virtual-env for the current image which is Bionic-based, I think a second branch for Focal so that we can have both available for a transition period.

**Comment by davidkarlsen** [comment]
@paolomainardi It fails with `jq: error (at /toolset.json:359): Cannot iterate over null (null)` - any idea on whats going on?
