### ISSUE TITLE
Use /home/runner (not /runner)

### ISSUE THREAD

**Issue by MPV** [evryfs/github-actions-runner#3]
Would you be open to using the same home dir as the standard GitHub hosted runners?

**Comment by MPV** [comment]
For example, I needed to patch another action to support non-standard homedir for these runners:
https://github.com/scala-steward-org/scala-steward-action/issues/40

Might be other actions where we could run into this problem too.

**Comment by davidkarlsen** [comment]
I think we should go as close to how it works on github native runners as possible.
Can you do a build (on linux) which simply does `pwd` as the build-step?

**Comment by MPV** [comment]
Yes, good idea. 
See https://github.com/evryfs/github-actions-runner/pull/4

**Comment by davidkarlsen** [comment]
Did you check what's the github runner default?

**Comment by MPV** [comment]
No, to be honest I just assumed it was `/home/runner` as there were actions that work and had hardcoded that as the used home dir (for example as in my linked scala steward example above). 😅

**Comment by MPV** [comment]
Searching for it in others' workflows, gives quite a few replies, suggesting the change might still be right, yes?

https://github.com/search?q=%22%2Fhome%2Frunner%22+path%3A.github%2Fworkflows&type=Code&ref=advsearch&l=&l=

**Comment by davidkarlsen** [comment]
@MPV https://github.com/evryfs/helm-charts/runs/722916637?check_suite_focus=true (the test step). So it is /home/runner

**Comment by MPV** [comment]
Nice, thanks for checking (properly 😅), as well as merging. 🎉

**Comment by davidkarlsen** [comment]
Thanks for the PR :)
