### ISSUE TITLE
Missing gcc

### ISSUE THREAD

**Issue by pcm32** [evryfs/github-actions-runner#35]
Thanks for this great operator and setup to run actions on k8s!

We started trying it and we noticed that the current latest image (ubuntu 20.04 tag I think) seems to be missing gcc:

https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/pull/211/checks?check_run_id=1452640729#step:8:260

We can probably do our own container FROM yours, but I guessed you might wanted to know given that this might be a general purpose action runner. Thanks!

**Comment by davidkarlsen** [comment]
Hi - thanks for the kind words!
I try to avoid adding too much to the image as it will become very bloated and heavy to pull. You can use actions similar to https://github.com/marketplace/actions/setup-go-environment to setup envs. You can of course also create a down-stream image where you add what's needed if it is a general need and a bit cumbersome to put into each workflow.
