### ISSUE TITLE
Runner POD restart causes error

### ISSUE THREAD

**Issue by dennybaa** [evryfs/github-actions-runner#43]
Howdy @davidkarlsen , it's not operator relevant I believe. Though pods might end up in crashloop, for easy reproduction I just kill Listner process and the error pops up:

`Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.`

**Comment by dennybaa** [comment]
That's what I expected... Though I've almost prepared my runners for cronjob runs and autoupdate, not sure when I plan to finish it however. I'm not going to run cronjob every 10 minutes or so not to abuse github actions with frequent runs, maybe every 6 hours is okay. During this lag runner autoupdate will aid and keep up runners in the functional state.

We can wait for https://github.com/actions/runner/pull/963, or I can make a PR with an extra logic which is in my runner https://github.com/dysnix/github-actions-runner/blob/master/entrypoint.sh#L16-L39 this make restart graceful on runner update.

**Comment by dennybaa** [comment]
@davidkarlsen Hey, wanted to update you. My runner version haven't survived the upgrade.  "container/persistence" part was okay, but after restart familiar thing... I haven't though yet about it, maybe it's really worth doing "./config.sh remove" then?

```
Cannot configure the runner because it is already configured. To reconfigure the runner, run 'config.cmd remove' or './config.sh remove' first.
```

**Comment by davidkarlsen** [comment]
@dennybaa I recommend avoiding runner auto-upgrades and baking it into the image instead.

**Comment by dennybaa** [comment]
@davidkarlsen What do you mean backing it into the image?

**Comment by davidkarlsen** [comment]
https://github.com/evryfs/github-actions-runner/blob/master/Dockerfile#L3 and then use the tags: https://github.com/evryfs/github-actions-runner/releases so that the image is immutable / does not self update the runner.

**Comment by dennybaa** [comment]
I do use tags as well as immutable images, just on kube side I copy runner over to emptydir volume and start from it. This mitigates the upgrade but requires de-registration (which I haven't approached yet). Without "auto-cron" every 5/10m CI workflow with auto-publish, I believe just simple use of an immutable image is no go for production. So if there's no one to release the new tag and upgrade an image to the newer version for several days... And the systems keep upgrading and crashlooping forever until someone pops up to perform the upgrade.

**Comment by dennybaa** [comment]
@davidkarlsen I could contribute, if we could draw common points. 
What I don't like in the current implementation:
- beefy images
- upgrade/restart not approached at all
- excessive amounts of layers
- no flavours
- no obuild image for derivatives

So we could solve these issues, in case you would like to. Please look at my fork https://github.com/dysnix/github-actions-runner, several of the issues I have addressed already.

**Comment by dennybaa** [comment]
@davidkarlsen And btw thank you for this great project it's really awesome!

**Comment by davidkarlsen** [comment]
Yeah, it's a bit of a PITA to maintain. I've been contemplating ditching it in favour of https://github.com/myoung34/docker-github-actions-runner which seems quite popular and well maintained, and rather create derivates of it.

Also - the integration with https://github.com/actions/virtual-environments is a bit hackish and flakey as that changes from time to time and there is no obvious way on how to use it.

I'll take a look on the fork when I get some time.

**Comment by davidkarlsen** [comment]
We build this branch now: https://github.com/evryfs/github-actions-runner/tree/myoung34-derivate -> https://quay.io/repository/evryfs/github-actions-runner?tab=tags

so you can try that instead.

Feel free to re-open should there be anything else.
