### ISSUE TITLE
Making /opt writeable

### ISSUE THREAD

**Issue by MPV** [evryfs/github-actions-runner#5]
I've tried an action that wants to create folders/files in `/opt` but isn't allowed. 

**Which way would make sense to change the runner image and/or operator podSpec to support this?**

Example of failing action output:

```
##[debug]EACCES: permission denied, mkdir '/opt/scala-steward'
##[error] ✕ Unable to create Scala Steward workspace
##[debug]Node Action run completed with exit code 1
```

And its implementation:

https://github.com/scala-steward-org/scala-steward-action/blob/master/src/files.ts

**Comment by davidkarlsen** [comment]
I would suggest to mount a volume to /opt in this case.

**Comment by MPV** [comment]
In this case, the authors of that action agreed that it made more sense to write files elsewhere and changed their code to write to the home dir instead:

https://github.com/scala-steward-org/scala-steward-action/pull/42

I'll try more actions going forward and see whether that was just an exception, or if there are more actions that assume other folders to be writeable. 😊
