### ISSUE TITLE
Sudo permissions missing for runner user?

### ISSUE THREAD

**Issue by bjw-s** [evryfs/github-actions-runner#51]
Hi,

I've been trying to run this image in conjunction with your awesome github-actions-runner-operator. So far it has been going pretty well, but I am running in to an issue where your image deviates a little bit from the official Github runner image.

In the official image, the `runner` user is allowed passwordless `sudo` access (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#administrative-privileges-of-github-hosted-runners), so that it can install system tools, etc.
Your image doesn't seem to do this, which makes some of my workflows fail with the followin error message:

```console
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

An example of an action that triggers this is this: https://github.com/marketplace/actions/setup-kubeval

Would you be open to supporting this behavior in your image? If you would be, I could set up a Pull Request for you to review.

**Comment by davidkarlsen** [comment]
Sure - a PR would be fine! 👍
