### ISSUE TITLE
Docker scan showing 35 vulnerabilities in image

### ISSUE THREAD

**Issue by sukumarp2020** [evryfs/github-actions-runner#69]
We see 35 CVEs for the latest image at [https://quay.io/repository/evryfs/github-actions-runner?tag=latest&tab=tags](https://quay.io/repository/evryfs/github-actions-runner?tag=latest&tab=tags).
Please let us know if they're gonna be fixed soon. 
https://quay.io/repository/evryfs/github-actions-runner/manifest/sha256:07868f15f3537b8f26f6f07eee58f740b707d0e1b564a290cbca1dc3cf0205ef?tab=vulnerabilities

Some of those vulnerabilities can be fixed by upgrading the versions. 

https://snyk.io/vuln/SNYK-UBUNTU2004-PYTHON38-1290411?utm_medium=Partner&utm_source=Docker&utm_campaign=Hub-integration

https://snyk.io/vuln/SNYK-UBUNTU2004-LIBXML2-609730?utm_medium=Partner&utm_source=Docker&utm_campaign=Hub-integration

**Comment by davidkarlsen** [comment]
We upgrade as soon as there are updated upstream images

**Comment by davidkarlsen** [comment]
https://quay.io/repository/evryfs/github-actions-runner/manifest/sha256:0b156f79a2a320dcb162d0f2d0c48f9ebb9e0a3133567b3acca00983f72c43ef?tab=vulnerabilities
