### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by brian-pickens** [evryfs/github-actions-runner#80]
Could you clarify the license that this repository is published under? I assume it is an oversight?

**Comment by davidkarlsen** [comment]
hmmm, this repo simply packs things in an image, so the license of what? The Dockerfile? All software contained in the image has it's own licenses.

**Comment by brian-pickens** [comment]
Yes, the docker file. Just want to make sure our organization is in compliance if we use your docker file as a base for our own docker file.

**Comment by davidkarlsen** [comment]
added license
