### ISSUE TITLE
Please upgrade runner to 2.281.1

### ISSUE THREAD

**Issue by MittWillson** [evryfs/github-actions-runner#81]
Maybe set a cronjob for check runner update and trigger action to build the latest image will be great

**Comment by Otterian** [comment]
Thank you for your feedback,

I have a PR open for a new release of the image with the updated runner (as well as updated virtualenvs)

We do have https://github.com/evryfs/github-actions-runner/issues/76 open, with the aim of implementing automatic updates. PRs are welcome :+1:

I'll close this once the PR is merged.

**Comment by Otterian** [comment]
Merged https://github.com/evryfs/github-actions-runner/pull/82
